/**
 * Auto-translation layer.
 *
 * Every JSX text node and a whitelist of text-bearing props are routed through
 * `autoTranslate()` by the JSX runtime shim (src/i18n/jsx-runtime.ts). The
 * dictionaries below are keyed by the exact English source string, and are
 * generated by `bun scripts/i18n-extract.ts` + `bun scripts/i18n-translate.ts`.
 *
 * English is always a pass-through, so the English pages are byte-identical to
 * what the components render.
 */
import type { Locale } from "./config";

import fr from "./auto/fr.json";
import ja from "./auto/ja.json";
import es from "./auto/es.json";
import pt from "./auto/pt.json";
import id from "./auto/id.json";

type Dict = Record<string, string>;

const DICTS: Partial<Record<Locale, Dict>> = {
  fr: fr as Dict,
  ja: ja as Dict,
  es: es as Dict,
  pt: pt as Dict,
  id: id as Dict,
};

let current: Locale = "en";

/** Set by the root layout on every render / navigation. */
export function setAutoLocale(locale: Locale) {
  current = locale;
}

export function getAutoLocale(): Locale {
  return current;
}

export function autoTranslateFor(locale: Locale, input: string): string {
  if (locale === "en") return input;
  const dict = DICTS[locale];
  if (!dict) return input;
  const key = input.trim();
  if (key.length < 2) return input;
  const hit = dict[key];
  if (!hit) return input;
  // Preserve any leading/trailing whitespace the JSX transform kept.
  return input === key ? hit : input.replace(key, hit);
}

export function autoTranslate(input: string): string {
  return autoTranslateFor(current, input);
}
