/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompressGifForDiscordRouteImport } from './routes/compress-gif-for-discord'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GifCompressorRouteImport } from './routes/gif-compressor'
import { Route as GifCropperRouteImport } from './routes/gif-cropper'
import { Route as GifResizerRouteImport } from './routes/gif-resizer'
import { Route as GifSpeedChangerRouteImport } from './routes/gif-speed-changer'
import { Route as GifSplitterRouteImport } from './routes/gif-splitter'
import { Route as GifToPngRouteImport } from './routes/gif-to-png'
import { Route as GifTrimmerRouteImport } from './routes/gif-trimmer'
import { Route as PngToGifRouteImport } from './routes/png-to-gif'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangCompressGifForDiscordRouteImport } from './routes/$lang/compress-gif-for-discord'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangGifCompressorRouteImport } from './routes/$lang/gif-compressor'
import { Route as LangGifCropperRouteImport } from './routes/$lang/gif-cropper'
import { Route as LangGifResizerRouteImport } from './routes/$lang/gif-resizer'
import { Route as LangGifSpeedChangerRouteImport } from './routes/$lang/gif-speed-changer'
import { Route as LangGifSplitterRouteImport } from './routes/$lang/gif-splitter'
import { Route as LangGifToPngRouteImport } from './routes/$lang/gif-to-png'
import { Route as LangGifTrimmerRouteImport } from './routes/$lang/gif-trimmer'
import { Route as LangPngToGifRouteImport } from './routes/$lang/png-to-gif'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangTermsRouteImport } from './routes/$lang/terms'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressGifForDiscordRoute = CompressGifForDiscordRouteImport.update({
  id: '/compress-gif-for-discord',
  path: '/compress-gif-for-discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GifCompressorRoute = GifCompressorRouteImport.update({
  id: '/gif-compressor',
  path: '/gif-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const GifCropperRoute = GifCropperRouteImport.update({
  id: '/gif-cropper',
  path: '/gif-cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const GifResizerRoute = GifResizerRouteImport.update({
  id: '/gif-resizer',
  path: '/gif-resizer',
  getParentRoute: () => rootRouteImport,
} as any)
const GifSpeedChangerRoute = GifSpeedChangerRouteImport.update({
  id: '/gif-speed-changer',
  path: '/gif-speed-changer',
  getParentRoute: () => rootRouteImport,
} as any)
const GifSplitterRoute = GifSplitterRouteImport.update({
  id: '/gif-splitter',
  path: '/gif-splitter',
  getParentRoute: () => rootRouteImport,
} as any)
const GifToPngRoute = GifToPngRouteImport.update({
  id: '/gif-to-png',
  path: '/gif-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const GifTrimmerRoute = GifTrimmerRouteImport.update({
  id: '/gif-trimmer',
  path: '/gif-trimmer',
  getParentRoute: () => rootRouteImport,
} as any)
const PngToGifRoute = PngToGifRouteImport.update({
  id: '/png-to-gif',
  path: '/png-to-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/$lang/about',
  path: '/$lang/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangCompressGifForDiscordRoute =
  LangCompressGifForDiscordRouteImport.update({
    id: '/$lang/compress-gif-for-discord',
    path: '/$lang/compress-gif-for-discord',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/$lang/contact',
  path: '/$lang/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGifCompressorRoute = LangGifCompressorRouteImport.update({
  id: '/$lang/gif-compressor',
  path: '/$lang/gif-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGifCropperRoute = LangGifCropperRouteImport.update({
  id: '/$lang/gif-cropper',
  path: '/$lang/gif-cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGifResizerRoute = LangGifResizerRouteImport.update({
  id: '/$lang/gif-resizer',
  path: '/$lang/gif-resizer',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGifSpeedChangerRoute = LangGifSpeedChangerRouteImport.update({
  id: '/$lang/gif-speed-changer',
  path: '/$lang/gif-speed-changer',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGifSplitterRoute = LangGifSplitterRouteImport.update({
  id: '/$lang/gif-splitter',
  path: '/$lang/gif-splitter',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGifToPngRoute = LangGifToPngRouteImport.update({
  id: '/$lang/gif-to-png',
  path: '/$lang/gif-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const LangGifTrimmerRoute = LangGifTrimmerRouteImport.update({
  id: '/$lang/gif-trimmer',
  path: '/$lang/gif-trimmer',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPngToGifRoute = LangPngToGifRouteImport.update({
  id: '/$lang/png-to-gif',
  path: '/$lang/png-to-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/$lang/privacy',
  path: '/$lang/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/$lang/terms',
  path: '/$lang/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-gif-for-discord': typeof CompressGifForDiscordRoute
  '/contact': typeof ContactRoute
  '/gif-compressor': typeof GifCompressorRoute
  '/gif-cropper': typeof GifCropperRoute
  '/gif-resizer': typeof GifResizerRoute
  '/gif-speed-changer': typeof GifSpeedChangerRoute
  '/gif-splitter': typeof GifSplitterRoute
  '/gif-to-png': typeof GifToPngRoute
  '/gif-trimmer': typeof GifTrimmerRoute
  '/png-to-gif': typeof PngToGifRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/compress-gif-for-discord': typeof LangCompressGifForDiscordRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gif-compressor': typeof LangGifCompressorRoute
  '/$lang/gif-cropper': typeof LangGifCropperRoute
  '/$lang/gif-resizer': typeof LangGifResizerRoute
  '/$lang/gif-speed-changer': typeof LangGifSpeedChangerRoute
  '/$lang/gif-splitter': typeof LangGifSplitterRoute
  '/$lang/gif-to-png': typeof LangGifToPngRoute
  '/$lang/gif-trimmer': typeof LangGifTrimmerRoute
  '/$lang/png-to-gif': typeof LangPngToGifRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/': typeof LangIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-gif-for-discord': typeof CompressGifForDiscordRoute
  '/contact': typeof ContactRoute
  '/gif-compressor': typeof GifCompressorRoute
  '/gif-cropper': typeof GifCropperRoute
  '/gif-resizer': typeof GifResizerRoute
  '/gif-speed-changer': typeof GifSpeedChangerRoute
  '/gif-splitter': typeof GifSplitterRoute
  '/gif-to-png': typeof GifToPngRoute
  '/gif-trimmer': typeof GifTrimmerRoute
  '/png-to-gif': typeof PngToGifRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/compress-gif-for-discord': typeof LangCompressGifForDiscordRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gif-compressor': typeof LangGifCompressorRoute
  '/$lang/gif-cropper': typeof LangGifCropperRoute
  '/$lang/gif-resizer': typeof LangGifResizerRoute
  '/$lang/gif-speed-changer': typeof LangGifSpeedChangerRoute
  '/$lang/gif-splitter': typeof LangGifSplitterRoute
  '/$lang/gif-to-png': typeof LangGifToPngRoute
  '/$lang/gif-trimmer': typeof LangGifTrimmerRoute
  '/$lang/png-to-gif': typeof LangPngToGifRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang': typeof LangIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-gif-for-discord': typeof CompressGifForDiscordRoute
  '/contact': typeof ContactRoute
  '/gif-compressor': typeof GifCompressorRoute
  '/gif-cropper': typeof GifCropperRoute
  '/gif-resizer': typeof GifResizerRoute
  '/gif-speed-changer': typeof GifSpeedChangerRoute
  '/gif-splitter': typeof GifSplitterRoute
  '/gif-to-png': typeof GifToPngRoute
  '/gif-trimmer': typeof GifTrimmerRoute
  '/png-to-gif': typeof PngToGifRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/compress-gif-for-discord': typeof LangCompressGifForDiscordRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gif-compressor': typeof LangGifCompressorRoute
  '/$lang/gif-cropper': typeof LangGifCropperRoute
  '/$lang/gif-resizer': typeof LangGifResizerRoute
  '/$lang/gif-speed-changer': typeof LangGifSpeedChangerRoute
  '/$lang/gif-splitter': typeof LangGifSplitterRoute
  '/$lang/gif-to-png': typeof LangGifToPngRoute
  '/$lang/gif-trimmer': typeof LangGifTrimmerRoute
  '/$lang/png-to-gif': typeof LangPngToGifRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/': typeof LangIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compress-gif-for-discord'
    | '/contact'
    | '/gif-compressor'
    | '/gif-cropper'
    | '/gif-resizer'
    | '/gif-speed-changer'
    | '/gif-splitter'
    | '/gif-to-png'
    | '/gif-trimmer'
    | '/png-to-gif'
    | '/privacy'
    | '/terms'
    | '/$lang/about'
    | '/$lang/compress-gif-for-discord'
    | '/$lang/contact'
    | '/$lang/gif-compressor'
    | '/$lang/gif-cropper'
    | '/$lang/gif-resizer'
    | '/$lang/gif-speed-changer'
    | '/$lang/gif-splitter'
    | '/$lang/gif-to-png'
    | '/$lang/gif-trimmer'
    | '/$lang/png-to-gif'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compress-gif-for-discord'
    | '/contact'
    | '/gif-compressor'
    | '/gif-cropper'
    | '/gif-resizer'
    | '/gif-speed-changer'
    | '/gif-splitter'
    | '/gif-to-png'
    | '/gif-trimmer'
    | '/png-to-gif'
    | '/privacy'
    | '/terms'
    | '/$lang/about'
    | '/$lang/compress-gif-for-discord'
    | '/$lang/contact'
    | '/$lang/gif-compressor'
    | '/$lang/gif-cropper'
    | '/$lang/gif-resizer'
    | '/$lang/gif-speed-changer'
    | '/$lang/gif-splitter'
    | '/$lang/gif-to-png'
    | '/$lang/gif-trimmer'
    | '/$lang/png-to-gif'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compress-gif-for-discord'
    | '/contact'
    | '/gif-compressor'
    | '/gif-cropper'
    | '/gif-resizer'
    | '/gif-speed-changer'
    | '/gif-splitter'
    | '/gif-to-png'
    | '/gif-trimmer'
    | '/png-to-gif'
    | '/privacy'
    | '/terms'
    | '/$lang/about'
    | '/$lang/compress-gif-for-discord'
    | '/$lang/contact'
    | '/$lang/gif-compressor'
    | '/$lang/gif-cropper'
    | '/$lang/gif-resizer'
    | '/$lang/gif-speed-changer'
    | '/$lang/gif-splitter'
    | '/$lang/gif-to-png'
    | '/$lang/gif-trimmer'
    | '/$lang/png-to-gif'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompressGifForDiscordRoute: typeof CompressGifForDiscordRoute
  ContactRoute: typeof ContactRoute
  GifCompressorRoute: typeof GifCompressorRoute
  GifCropperRoute: typeof GifCropperRoute
  GifResizerRoute: typeof GifResizerRoute
  GifSpeedChangerRoute: typeof GifSpeedChangerRoute
  GifSplitterRoute: typeof GifSplitterRoute
  GifToPngRoute: typeof GifToPngRoute
  GifTrimmerRoute: typeof GifTrimmerRoute
  PngToGifRoute: typeof PngToGifRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  LangAboutRoute: typeof LangAboutRoute
  LangCompressGifForDiscordRoute: typeof LangCompressGifForDiscordRoute
  LangContactRoute: typeof LangContactRoute
  LangGifCompressorRoute: typeof LangGifCompressorRoute
  LangGifCropperRoute: typeof LangGifCropperRoute
  LangGifResizerRoute: typeof LangGifResizerRoute
  LangGifSpeedChangerRoute: typeof LangGifSpeedChangerRoute
  LangGifSplitterRoute: typeof LangGifSplitterRoute
  LangGifToPngRoute: typeof LangGifToPngRoute
  LangGifTrimmerRoute: typeof LangGifTrimmerRoute
  LangPngToGifRoute: typeof LangPngToGifRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangTermsRoute: typeof LangTermsRoute
  LangIndexRoute: typeof LangIndexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-gif-for-discord': {
      id: '/compress-gif-for-discord'
      path: '/compress-gif-for-discord'
      fullPath: '/compress-gif-for-discord'
      preLoaderRoute: typeof CompressGifForDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-compressor': {
      id: '/gif-compressor'
      path: '/gif-compressor'
      fullPath: '/gif-compressor'
      preLoaderRoute: typeof GifCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-cropper': {
      id: '/gif-cropper'
      path: '/gif-cropper'
      fullPath: '/gif-cropper'
      preLoaderRoute: typeof GifCropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-resizer': {
      id: '/gif-resizer'
      path: '/gif-resizer'
      fullPath: '/gif-resizer'
      preLoaderRoute: typeof GifResizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-speed-changer': {
      id: '/gif-speed-changer'
      path: '/gif-speed-changer'
      fullPath: '/gif-speed-changer'
      preLoaderRoute: typeof GifSpeedChangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-splitter': {
      id: '/gif-splitter'
      path: '/gif-splitter'
      fullPath: '/gif-splitter'
      preLoaderRoute: typeof GifSplitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-to-png': {
      id: '/gif-to-png'
      path: '/gif-to-png'
      fullPath: '/gif-to-png'
      preLoaderRoute: typeof GifToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-trimmer': {
      id: '/gif-trimmer'
      path: '/gif-trimmer'
      fullPath: '/gif-trimmer'
      preLoaderRoute: typeof GifTrimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/png-to-gif': {
      id: '/png-to-gif'
      path: '/png-to-gif'
      fullPath: '/png-to-gif'
      preLoaderRoute: typeof PngToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/$lang/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/compress-gif-for-discord': {
      id: '/$lang/compress-gif-for-discord'
      path: '/$lang/compress-gif-for-discord'
      fullPath: '/$lang/compress-gif-for-discord'
      preLoaderRoute: typeof LangCompressGifForDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/$lang/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gif-compressor': {
      id: '/$lang/gif-compressor'
      path: '/$lang/gif-compressor'
      fullPath: '/$lang/gif-compressor'
      preLoaderRoute: typeof LangGifCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gif-cropper': {
      id: '/$lang/gif-cropper'
      path: '/$lang/gif-cropper'
      fullPath: '/$lang/gif-cropper'
      preLoaderRoute: typeof LangGifCropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gif-resizer': {
      id: '/$lang/gif-resizer'
      path: '/$lang/gif-resizer'
      fullPath: '/$lang/gif-resizer'
      preLoaderRoute: typeof LangGifResizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gif-speed-changer': {
      id: '/$lang/gif-speed-changer'
      path: '/$lang/gif-speed-changer'
      fullPath: '/$lang/gif-speed-changer'
      preLoaderRoute: typeof LangGifSpeedChangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gif-splitter': {
      id: '/$lang/gif-splitter'
      path: '/$lang/gif-splitter'
      fullPath: '/$lang/gif-splitter'
      preLoaderRoute: typeof LangGifSplitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gif-to-png': {
      id: '/$lang/gif-to-png'
      path: '/$lang/gif-to-png'
      fullPath: '/$lang/gif-to-png'
      preLoaderRoute: typeof LangGifToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/gif-trimmer': {
      id: '/$lang/gif-trimmer'
      path: '/$lang/gif-trimmer'
      fullPath: '/$lang/gif-trimmer'
      preLoaderRoute: typeof LangGifTrimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/png-to-gif': {
      id: '/$lang/png-to-gif'
      path: '/$lang/png-to-gif'
      fullPath: '/$lang/png-to-gif'
      preLoaderRoute: typeof LangPngToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/$lang/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/$lang/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompressGifForDiscordRoute: CompressGifForDiscordRoute,
  ContactRoute: ContactRoute,
  GifCompressorRoute: GifCompressorRoute,
  GifCropperRoute: GifCropperRoute,
  GifResizerRoute: GifResizerRoute,
  GifSpeedChangerRoute: GifSpeedChangerRoute,
  GifSplitterRoute: GifSplitterRoute,
  GifToPngRoute: GifToPngRoute,
  GifTrimmerRoute: GifTrimmerRoute,
  PngToGifRoute: PngToGifRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  LangAboutRoute: LangAboutRoute,
  LangCompressGifForDiscordRoute: LangCompressGifForDiscordRoute,
  LangContactRoute: LangContactRoute,
  LangGifCompressorRoute: LangGifCompressorRoute,
  LangGifCropperRoute: LangGifCropperRoute,
  LangGifResizerRoute: LangGifResizerRoute,
  LangGifSpeedChangerRoute: LangGifSpeedChangerRoute,
  LangGifSplitterRoute: LangGifSplitterRoute,
  LangGifToPngRoute: LangGifToPngRoute,
  LangGifTrimmerRoute: LangGifTrimmerRoute,
  LangPngToGifRoute: LangPngToGifRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangTermsRoute: LangTermsRoute,
  LangIndexRoute: LangIndexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
