/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompressGifForDiscordRouteImport } from './routes/compress-gif-for-discord'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GifCompressorRouteImport } from './routes/gif-compressor'
import { Route as GifCropperRouteImport } from './routes/gif-cropper'
import { Route as GifResizerRouteImport } from './routes/gif-resizer'
import { Route as GifSpeedChangerRouteImport } from './routes/gif-speed-changer'
import { Route as GifSplitterRouteImport } from './routes/gif-splitter'
import { Route as GifToPngRouteImport } from './routes/gif-to-png'
import { Route as GifTrimmerRouteImport } from './routes/gif-trimmer'
import { Route as PngToGifRouteImport } from './routes/png-to-gif'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressGifForDiscordRoute = CompressGifForDiscordRouteImport.update({
  id: '/compress-gif-for-discord',
  path: '/compress-gif-for-discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GifCompressorRoute = GifCompressorRouteImport.update({
  id: '/gif-compressor',
  path: '/gif-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const GifCropperRoute = GifCropperRouteImport.update({
  id: '/gif-cropper',
  path: '/gif-cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const GifResizerRoute = GifResizerRouteImport.update({
  id: '/gif-resizer',
  path: '/gif-resizer',
  getParentRoute: () => rootRouteImport,
} as any)
const GifSpeedChangerRoute = GifSpeedChangerRouteImport.update({
  id: '/gif-speed-changer',
  path: '/gif-speed-changer',
  getParentRoute: () => rootRouteImport,
} as any)
const GifSplitterRoute = GifSplitterRouteImport.update({
  id: '/gif-splitter',
  path: '/gif-splitter',
  getParentRoute: () => rootRouteImport,
} as any)
const GifToPngRoute = GifToPngRouteImport.update({
  id: '/gif-to-png',
  path: '/gif-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const GifTrimmerRoute = GifTrimmerRouteImport.update({
  id: '/gif-trimmer',
  path: '/gif-trimmer',
  getParentRoute: () => rootRouteImport,
} as any)
const PngToGifRoute = PngToGifRouteImport.update({
  id: '/png-to-gif',
  path: '/png-to-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/compress-gif-for-discord': typeof CompressGifForDiscordRoute
  '/contact': typeof ContactRoute
  '/gif-compressor': typeof GifCompressorRoute
  '/gif-cropper': typeof GifCropperRoute
  '/gif-resizer': typeof GifResizerRoute
  '/gif-speed-changer': typeof GifSpeedChangerRoute
  '/gif-splitter': typeof GifSplitterRoute
  '/gif-to-png': typeof GifToPngRoute
  '/gif-trimmer': typeof GifTrimmerRoute
  '/png-to-gif': typeof PngToGifRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/compress-gif-for-discord': typeof CompressGifForDiscordRoute
  '/contact': typeof ContactRoute
  '/gif-compressor': typeof GifCompressorRoute
  '/gif-cropper': typeof GifCropperRoute
  '/gif-resizer': typeof GifResizerRoute
  '/gif-speed-changer': typeof GifSpeedChangerRoute
  '/gif-splitter': typeof GifSplitterRoute
  '/gif-to-png': typeof GifToPngRoute
  '/gif-trimmer': typeof GifTrimmerRoute
  '/png-to-gif': typeof PngToGifRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/compress-gif-for-discord': typeof CompressGifForDiscordRoute
  '/contact': typeof ContactRoute
  '/gif-compressor': typeof GifCompressorRoute
  '/gif-cropper': typeof GifCropperRoute
  '/gif-resizer': typeof GifResizerRoute
  '/gif-speed-changer': typeof GifSpeedChangerRoute
  '/gif-splitter': typeof GifSplitterRoute
  '/gif-to-png': typeof GifToPngRoute
  '/gif-trimmer': typeof GifTrimmerRoute
  '/png-to-gif': typeof PngToGifRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/compress-gif-for-discord'
    | '/contact'
    | '/gif-compressor'
    | '/gif-cropper'
    | '/gif-resizer'
    | '/gif-speed-changer'
    | '/gif-splitter'
    | '/gif-to-png'
    | '/gif-trimmer'
    | '/png-to-gif'
    | '/privacy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/compress-gif-for-discord'
    | '/contact'
    | '/gif-compressor'
    | '/gif-cropper'
    | '/gif-resizer'
    | '/gif-speed-changer'
    | '/gif-splitter'
    | '/gif-to-png'
    | '/gif-trimmer'
    | '/png-to-gif'
    | '/privacy'
    | '/terms'
  id:
    | '__root__'
    | '/about'
    | '/compress-gif-for-discord'
    | '/contact'
    | '/gif-compressor'
    | '/gif-cropper'
    | '/gif-resizer'
    | '/gif-speed-changer'
    | '/gif-splitter'
    | '/gif-to-png'
    | '/gif-trimmer'
    | '/png-to-gif'
    | '/privacy'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  CompressGifForDiscordRoute: typeof CompressGifForDiscordRoute
  ContactRoute: typeof ContactRoute
  GifCompressorRoute: typeof GifCompressorRoute
  GifCropperRoute: typeof GifCropperRoute
  GifResizerRoute: typeof GifResizerRoute
  GifSpeedChangerRoute: typeof GifSpeedChangerRoute
  GifSplitterRoute: typeof GifSplitterRoute
  GifToPngRoute: typeof GifToPngRoute
  GifTrimmerRoute: typeof GifTrimmerRoute
  PngToGifRoute: typeof PngToGifRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-gif-for-discord': {
      id: '/compress-gif-for-discord'
      path: '/compress-gif-for-discord'
      fullPath: '/compress-gif-for-discord'
      preLoaderRoute: typeof CompressGifForDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-compressor': {
      id: '/gif-compressor'
      path: '/gif-compressor'
      fullPath: '/gif-compressor'
      preLoaderRoute: typeof GifCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-cropper': {
      id: '/gif-cropper'
      path: '/gif-cropper'
      fullPath: '/gif-cropper'
      preLoaderRoute: typeof GifCropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-resizer': {
      id: '/gif-resizer'
      path: '/gif-resizer'
      fullPath: '/gif-resizer'
      preLoaderRoute: typeof GifResizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-speed-changer': {
      id: '/gif-speed-changer'
      path: '/gif-speed-changer'
      fullPath: '/gif-speed-changer'
      preLoaderRoute: typeof GifSpeedChangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-splitter': {
      id: '/gif-splitter'
      path: '/gif-splitter'
      fullPath: '/gif-splitter'
      preLoaderRoute: typeof GifSplitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-to-png': {
      id: '/gif-to-png'
      path: '/gif-to-png'
      fullPath: '/gif-to-png'
      preLoaderRoute: typeof GifToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-trimmer': {
      id: '/gif-trimmer'
      path: '/gif-trimmer'
      fullPath: '/gif-trimmer'
      preLoaderRoute: typeof GifTrimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/png-to-gif': {
      id: '/png-to-gif'
      path: '/png-to-gif'
      fullPath: '/png-to-gif'
      preLoaderRoute: typeof PngToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  CompressGifForDiscordRoute: CompressGifForDiscordRoute,
  ContactRoute: ContactRoute,
  GifCompressorRoute: GifCompressorRoute,
  GifCropperRoute: GifCropperRoute,
  GifResizerRoute: GifResizerRoute,
  GifSpeedChangerRoute: GifSpeedChangerRoute,
  GifSplitterRoute: GifSplitterRoute,
  GifToPngRoute: GifToPngRoute,
  GifTrimmerRoute: GifTrimmerRoute,
  PngToGifRoute: PngToGifRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
